version: "3"

services:
  scylla:
    image: scylladb/scylla:latest
    networks:
      - scylla
    volumes:
      - ./data/scylla:/var/lib/scylla
    command: "--smp 1 --memory 256M --experimental 1"
    ports:
      - 9042:9042

networks:
  scylla:
